post_install() {
    EXTRAMODULES=extramodules-4.6-rt-MANJARO
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
    echo 'In order to use catalyst module, reboot the system.'
}

post_upgrade() {
    EXTRAMODULES=extramodules-4.6-rt-MANJARO
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
}

post_remove() {
    EXTRAMODULES=extramodules-4.6-rt-MANJARO
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
}
